# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvZpq2ml7ohNxOnZTiBym3v_Iss-bsjC
"""

import random
from typing import List

def input_check() -> str:
    """
    Prompt the user to enter a 4-digit number.

    Checks:
    - The input must have exactly 4 digits.
    - All digits must be unique.
    - The first digit cannot be '0'.

    Returns:
        str: The valid 4-digit number entered by the user.
    """
    while True:
        user_input: str = input(">>>>: ")

        if len(user_input) == 4 and user_input.isdigit() and len(set(user_input)) == 4 and user_input[0] != '0':
            return user_input
        else:
            print("Invalid input! Try again.")


def generate_number() -> List[int]:
    """
    Generate a random 4-digit number with unique digits.

    Rules:
    - First digit cannot be 0.
    - All digits must be unique.

    Returns:
        List[int]: A list of 4 unique digits as integers.
    """
    options: List[int] = [0,1,2,3,4,5,6,7,8,9]
    digits: List[int] = []

    first: int = random.choice(options[1:])
    digits.append(first)

    remaining_options: List[int] = options.copy()
    remaining_options.remove(first)

    for _ in range(3):
        new_digit: int = random.choice(remaining_options)
        digits.append(new_digit)
        remaining_options.remove(new_digit)

    return digits


# Game setup
computer_choices: List[str] = [str(x) for x in generate_number()]
separator: str = '--------------------------------------------'
attempts: int = 0

print("Hi there!")
print(separator)
print("I´ve generated a random 4 digit number for you.")
print("Let´s play a bulls and cows game.")
print(separator)
print("Enter a number:")

# Main game loop
while True:
    cow: int = 0
    bull: int = 0
    attempts += 1
    print(separator)

    player_number: str = input_check()

    for i in range(4):
        if player_number[i] == computer_choices[i]:
            bull += 1
        elif player_number[i] in computer_choices:
            cow += 1

    if bull == 4:
        print(f"Correct, you´ve guessed the right number in: {attempts} guesses!")
        print(separator)
        print("That´s amazing!")
        break
    elif bull <= 1 and cow <= 1:
        print(f"bull: {bull}, cow: {cow}")
    elif bull > 1 and cow > 1:
        print(f"bulls: {bull}, cows: {cow}")
    elif bull > 1:
        print(f"bulls: {bull}, cow: {cow}")
    elif cow > 1:
        print(f"bull: {bull}, cows: {cow}")